FROM ubuntu:22.04
ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get update && apt-get install -y \
  build-essential cmake pkg-config git \
  protobuf-compiler libprotobuf-dev \
  libgrpc-dev libgrpc++-dev \
  libboost-all-dev nlohmann-json3-dev ca-certificates \
  libssl-dev protobuf-compiler-grpc && \
  rm -rf /var/lib/apt/lists/*
WORKDIR /app
COPY . .
RUN cmake -S . -B build -DCMAKE_BUILD_TYPE=Release && cmake --build build -j
CMD ["./build/aggregator/aggregator"]
