name: CI (docker-compose)

on:
  push:
    branches: ["**"]
  pull_request:

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  compose-test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build images
        working-directory: docker
        run: docker compose build --no-cache aggregator

      - name: Run tests in container
        working-directory: docker
        run: docker compose run --rm aggregator ctest -V --test-dir build
